### ISSUE TITLE
[iOS] Umbrella header for module 'KlarnaMobileSDK' does not include header 'KlarnaMobileSDKPostfix.h'

### ISSUE THREAD

**Issue by javiervg-itx** [klarna/klarna-mobile-sdk#202]
**Describe the bug**
After upgrading from version 2.1.7 to 2.6.6 and compiling, the following errors are thrown:
- `Umbrella header for module 'KlarnaMobileSDK' does not include header 'KlarnaMobileSDKPostfix.h'`
- `Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)` in KlarnaMobileSDK-Swift.h
- `Could not build module 'KlarnaMobileSDK'`

**To Reproduce**
1. Changed version of the SPM Klarna package from 2.1.7 to 2.6.6
2. Compile
3. Also tested cleaning derived data and build folder before compilation

**Expected behavior**
Correct compilation of the module

**Device and version:**
 - Xcode 14.2, building for simulator on a M1
 - Klarna In-App SDK version: 2.6.6 (tested also with 2.4.0 onwards)

**Additional context**
I found that the only way to compile is disabling the following compiler options:
- `Treat warnings as errors` in Apple Clang
- `Treat warnings as errors` in Swift Compiler
but, of couse, we would like to have these settings active as before.

**Comment by polar133** [comment]
Hi @javiervg-itx Thanks for the report. 

We try to replicate the same issue but for us it's working fine. What i can suggest is try to clean the SPM cache. Please give a try to the suggestions posted on https://stackoverflow.com/questions/72788019/where-is-swift-package-manager-cache-located-swift-5-7/72838880#72838880

**Comment by alanperezoc** [comment]
Hi! We are facing exactly the same issue when getting the SDK via Cocoapods.
Same versions and device .

**Comment by polar133** [comment]
Hi @alanperezoc. From what version are you updating ? Can you give a try and specify an older version and see if the error is the same ? Have you tried the same approach to clean the data ?

**Comment by javiervg-itx** [comment]
Hi @polar133, tried cleaning the SPM cache but the error persists

**Comment by polar133** [comment]
@javiervg-itx thanks for the update. Can you please try again with a lower version? e.g 2.6.2

**Comment by javiervg-itx** [comment]
@polar133 Yes, tried now with 2.6.2 and same error.

Investigating, I've seen this: https://github.com/stripe/stripe-ios/issues/1772 where the same error ocurred with another library. It looks like they resolved with a fix inside the library but no other info was added to the issue...

**Comment by polar133** [comment]
Thanks. We will investigate a little more and be back once we have some updates to share.

**Comment by polar133** [comment]
We are working on a possible fix. It will be available on the next release early next week. 🤞

**Comment by marc-op** [comment]
Hello @polar133 ,

Do you have any updates on this matter?

Thanks.

**Comment by polar133** [comment]
Hi @marc-op @javiervg-itx @alanperezoc, We just released 2.6.7 that should address this issue. Please give a try and let us know how it goes. 👍

**Comment by alanperezoc** [comment]
thanks @polar133 , we'll give it a try on next days!

**Comment by pedronl** [comment]
Hi @polar133, we´ve tried with the 2.6.7 version but we´re still finding these errors:
- Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) in KlarnaMobileSDK-Swift.h
- Could not build module 'KlarnaMobileSDK'

We´ve tried reseting the SPM cache, cleaning derived data and doing a clean build but the errors persist 😕

**Comment by polar133** [comment]
Hi @pedronl, thank you for bringing this to our attention. We are actively working on a solution and aim to resolve it asap. We apologize for any inconvenience this may have caused.

**Comment by polar133** [comment]
@pedronl Should be fixed on the new version 2.6.8. Please, give a try and let us know how it goes. Thanks and again sorry for any inconvenience. This should have been fixed on the prev. release.

**Comment by javiervg-itx** [comment]
Hi @polar133, version 2.6.8 solved the problem. Thank you!

**Comment by polar133** [comment]
Thanks for the update @javiervg-itx. Since it's fixed, i will close the issue. If there is something else please don't hesitate to open it again.  👍
